spring:
  h2.console:
    enabled: true
    path: '/console'

  datasource:
    url: 'jdbc:h2:file:./my-budget-db'

  jpa:
    hibernate:
      ddl-auto: create-drop

  security:
    user:
      name: admin
      password: admin

server:
  port: 8180
  servlet:
    context-path: /mybudget