spring:
  h2.console:
    enabled: true
    path: '/console'


  datasource:
    platform: h2
    url: 'jdbc:h2:file:./my-budget-db'



  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true



#server:
#  port: 8180
#  servlet:
#    context-path: /mybudget
